---
# Configuration of integration tests on travis-ci.org
language: python
dist: trusty

services:
  - postgresql
  - rabbitmq

addons:
  postgresql: "9.6"

env:
  global:
  - AIIDA_TEST_BACKEND: django
  # show timings of tests
  - PYTEST_ADDOPTS: --durations=0

matrix:
  include:
  # python27, develop aiida-core
  - name: "python-2.7 (django)"
    python: 2.7
    env:
      TEST_TYPE: tests
  - name: "python-2.7 (sqla)"
    python: 2.7
    env:
      TEST_TYPE: tests
      AIIDA_TEST_BACKEND: sqlalchemy
  - name: "python-2.7 (pre-commit)"
    python: 2.7
    env:
      TEST_TYPE: pre-commit

  # python36, develop aiida-core
  - name: "python-3.6 (django)"
    python: 3.6
    env:
      AIIDA_VERSION: develop
      TEST_TYPE: tests
  - name: "python-3.6 (sqla)"
    python: 3.6
    env:
      TEST_TYPE: tests
      AIIDA_TEST_BACKEND: sqlalchemy
  - name: "python-3.6 (docs)"
    python: 3.6
    env:
      TEST_TYPE: docs
      READTHEDOCS: 'True'
  - name: "python-3.6 (pre-commit)"
    python: 3.6
    env:
      AIIDA_VERSION: develop
      TEST_TYPE: pre-commit

  # Remove this to enforce the AiiDA coding style
  allow_failures: 
  - TEST_TYPE: pre-commit

before_install:
# Upgrade pip setuptools and wheel
- pip install -U pip wheel setuptools

install:
- pip install -e .[testing,docs,pre-commit]
- reentry scan -r aiida
- pip install coveralls

script:
- if [ "$TEST_TYPE" == "tests" ] ; then py.test --cov aiida_gaussian --cov-append . ; fi  # runs unit tests
- if [ "$TEST_TYPE" == "docs" ] ; then cd docs; make; fi  # creates documentation
# runs precommit checks (failures allowed)
- if [ "$TEST_TYPE" == "pre-commit" ] ; then pre-commit install; pre-commit run --all-files || ( git status --short; git diff ; exit 1 ); fi

after_success:
- coveralls
